version: '3.8'

services:
  onixproject.api:
    image: ${DOCKER_REGISTRY-}onixprojectapi
    build:
      context: .
      dockerfile: src/OnixProject.Api/Dockerfile
    networks:
      - backend

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    ports:
      - 5432:5432
  redis:
    image: redis
    networks:
      - backend
  rabbitmq:
    image: rabbitmq
    networks:
      - backend
networks:
  backend: